### ISSUE TITLE
Detectron issue

### ISSUE THREAD

**Issue by Daniel-1597** [AlejandroBarrera/birdnet2#1]
![IMG_20200527_140525](https://user-images.githubusercontent.com/53418529/82997090-8b531980-a023-11ea-912e-c8e464fbcd23.jpg)

**Comment by AlejandroBarrera** [comment]
Please check if you have installed detectron2 correctly and are in the right conda environment. If you have any questions about the installation of [detectron]([https://github.com/facebookresearch/detectron2](https://github.com/facebookresearch/detectron2)), please refer to the repository first.

**Comment by Petros626** [comment]
@Daniel-1597 did you succesfully trained with this repo?
